name: Build techno

on:
  push:
    branches:
      - main  # Déclenchement du workflow à chaque push sur main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Installation des dépendances
        run: npm install

      - name: Build du site
        run: npm run build

      - name: Déploiement sur la branche `build`
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout --orphan build
          git rm -rf .
          mv build/* .
          git add .
          git commit -m "Mise à jour du build [GitHub Actions]"
          git push -f origin build